// ── ARCANE_RANK_COPIES ───────────────────────────────────────────
// Copies of an arcane required to reach each rank (index = rank)
const ARCANE_RANK_COPIES = [1,3,6,10,15,21];

// ── ARCANES ──────────────────────────────────────────────────────
// [name, type, acquisition, maxRank, rarity, tradable, category]
// acquisition: array of sources. tradable: 1 if player-tradable.
const ARCANES = [
  ['Primary Deadhead','Primary',['Acolytes'],5,'Rare',1,'Steel'],
  ['Primary Dexterity','Primary',['Acolytes'],5,'Rare',1,'Steel'],
  ['Primary Merciless','Primary',['Acolytes'],5,'Rare',1,'Steel'],
  ['Secondary Deadhead','Secondary',['Acolytes'],5,'Rare',1,'Steel'],
  ['Secondary Dexterity','Secondary',['Acolytes'],5,'Rare',1,'Steel'],
  ['Secondary Merciless','Secondary',['Acolytes'],5,'Rare',1,'Steel'],
  ['Arcane Blade Charger','Warframe',['Arbitrations'],5,'Rare',1,'Steel'],
  ['Arcane Bodyguard','Warframe',['Arbitrations'],5,'Rare',1,'Steel'],
  ['Arcane Pistoleer','Warframe',['Arbitrations'],5,'Rare',1,'Steel'],
  ['Arcane Primary Charger','Warframe',['Arbitrations'],5,'Rare',1,'Steel'],
  ['Arcane Tanker','Warframe',['Arbitrations'],5,'Rare',1,'Steel'],
  ['Arcane Battery','Warframe',['Ascension'],5,'Rare',1,'Ascension'],
  ['Arcane Ice Storm','Warframe',['Ascension'],5,'Rare',1,'Ascension'],
  ['Melee Afflictions','Melee',['Ascension'],5,'Rare',1,'Ascension'],
  ['Secondary Fortifier','Secondary',['Ascension'],5,'Rare',1,'Ascension'],
  ['Secondary Surge','Secondary',['Ascension'],5,'Rare',1,'Ascension'],
  ['Melee Animosity','Melee',['Cavia'],5,'Rare',1,'Cavia'],
  ['Melee Crescendo','Melee',['Cavia'],5,'Legendary',1,'Cavia'],
  ['Melee Duplicate','Melee',['Cavia'],5,'Legendary',1,'Cavia'],
  ['Melee Exposure','Melee',['Cavia'],5,'Rare',1,'Cavia'],
  ['Melee Fortification','Melee',['Cavia'],5,'Common',1,'Cavia'],
  ['Melee Influence','Melee',['Cavia'],5,'Rare',1,'Cavia'],
  ['Melee Retaliation','Melee',['Cavia'],5,'Common',1,'Cavia'],
  ['Melee Vortex','Melee',['Cavia'],5,'Rare',1,'Cavia'],
  ['Arcane Blessing','Warframe',['Conjunction Survival'],5,'Rare',1,'Holdfasts'],
  ['Arcane Rise','Warframe',['Conjunction Survival'],5,'Rare',1,'Holdfasts'],
  ['Conjunction Voltage','Secondary',['Conjunction Survival'],5,'Rare',1,'Holdfasts'],
  ['Primary Frostbite','Primary',['Conjunction Survival'],5,'Rare',1,'Holdfasts'],
  ['Akimbo Slip Shot','Secondary',['Duviri'],5,'Rare',1,'Duviri'],
  ['Arcane Intention','Warframe',['Duviri'],5,'Uncommon',1,'Duviri'],
  ['Arcane Power Ramp','Warframe',['Duviri'],5,'Rare',1,'Duviri'],
  ['Arcane Reaper','Warframe',['Duviri'],5,'Legendary',1,'Duviri'],
  ['Longbow Sharpshot','Primary',['Duviri'],5,'Legendary',1,'Duviri'],
  ['Magus Aggress','Operator',['Duviri'],5,'Uncommon',1,'Duviri'],
  ['Primary Blight','Primary',['Duviri'],5,'Rare',1,'Duviri'],
  ['Primary Exhilarate','Primary',['Duviri'],5,'Rare',1,'Duviri'],
  ['Primary Obstruct','Primary',['Duviri'],5,'Rare',1,'Duviri'],
  ['Secondary Outburst','Secondary',['Duviri'],5,'Rare',1,'Duviri'],
  ['Secondary Shiver','Secondary',['Duviri'],5,'Legendary',1,'Duviri'],
  ['Shotgun Vendetta','Primary',['Duviri'],5,'Rare',1,'Duviri'],
  ['Arcane Acceleration','Warframe',['Gantulyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Aegis','Warframe',['Gantulyst','Orphix'],5,'Rare',1,'Eidolon'],
  ['Arcane Agility','Warframe',['Gantulyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Awakening','Warframe',['Gantulyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Eruption','Warframe',['Gantulyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Guardian','Warframe',['Gantulyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Phantasm','Warframe',['Gantulyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Precision','Warframe',['Gantulyst','Orphix'],5,'Rare',1,'Eidolon'],
  ['Arcane Pulse','Warframe',['Gantulyst','Orphix'],5,'Rare',1,'Eidolon'],
  ['Arcane Strike','Warframe',['Gantulyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Ultimatum','Warframe',['Gantulyst','Orphix'],5,'Rare',1,'Eidolon'],
  ['Arcane Bellicose','Warframe',['Hollvania'],5,'Rare',1,'Hollvania'],
  ['Arcane Camisado','Warframe',['Hollvania'],5,'Rare',1,'Hollvania'],
  ['Arcane Crepuscular','Warframe',['Hollvania'],5,'Rare',1,'Hollvania'],
  ['Arcane Escapist','Warframe',['Hollvania'],5,'Legendary',1,'Hollvania'],
  ['Arcane Hot Shot','Warframe',['Hollvania'],5,'Legendary',1,'Hollvania'],
  ['Arcane Impetus','Warframe',['Hollvania'],5,'Rare',1,'Hollvania'],
  ['Arcane Truculence','Warframe',['Hollvania'],5,'Rare',1,'Hollvania'],
  ['Arcane Universal Fallout','Warframe',['Hollvania'],5,'Legendary',1,'Hollvania'],
  ['Melee Doughty','Melee',['Hollvania'],5,'Rare',1,'Hollvania'],
  ['Primary Crux','Primary',['Hollvania'],5,'Rare',1,'Hollvania'],
  ['Secondary Enervate','Secondary',['Hollvania'],5,'Rare',1,'Hollvania'],
  ['Arcane Arachne','Warframe',['Hydrolyst','Orphix'],5,'Rare',1,'Eidolon'],
  ['Arcane Avenger','Warframe',['Hydrolyst','Orphix'],5,'Rare',1,'Eidolon'],
  ['Arcane Barrier','Warframe',['Hydrolyst','Orphix'],5,'Legendary',1,'Eidolon'],
  ['Arcane Energize','Warframe',['Hydrolyst','Orphix'],5,'Legendary',1,'Eidolon'],
  ['Arcane Fury','Warframe',['Hydrolyst','Orphix'],5,'Rare',1,'Eidolon'],
  ['Arcane Grace','Warframe',['Hydrolyst','Orphix'],5,'Legendary',1,'Eidolon'],
  ['Arcane Rage','Warframe',['Hydrolyst','Orphix'],5,'Rare',1,'Eidolon'],
  ['Arcane Trickery','Warframe',['Hydrolyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Velocity','Warframe',['Hydrolyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Residual Boils','Kitgun',['Isolation Vaults'],3,'Rare',1,'Necralisk'],
  ['Residual Malodor','Kitgun',['Isolation Vaults'],3,'Rare',1,'Necralisk'],
  ['Residual Shock','Kitgun',['Isolation Vaults'],3,'Rare',1,'Necralisk'],
  ['Residual Viremia','Kitgun',['Isolation Vaults'],3,'Rare',1,'Necralisk'],
  ['Theorem Contagion','Warframe',['Isolation Vaults'],5,'Rare',1,'Necralisk'],
  ['Theorem Demulcent','Warframe',['Isolation Vaults'],5,'Rare',1,'Necralisk'],
  ['Theorem Infection','Warframe',['Isolation Vaults'],5,'Rare',1,'Necralisk'],
  ['Arcane Double Back','Warframe',['Mirror Defense'],5,'Rare',1,'Necralisk'],
  ['Arcane Steadfast','Warframe',['Mirror Defense'],5,'Rare',1,'Necralisk'],
  ['Primary Plated Round','Primary',['Mirror Defense'],5,'Rare',1,'Necralisk'],
  ['Secondary Encumber','Secondary',['Mirror Defense'],5,'Rare',1,'Necralisk'],
  ['Secondary Kinship','Secondary',['Mirror Defense'],5,'Rare',1,'Necralisk'],
  ['Exodia Brave','Zaw',['Ostron'],3,'Rare',1,'Ostron'],
  ['Exodia Force','Zaw',['Ostron'],3,'Rare',1,'Ostron'],
  ['Exodia Hunt','Zaw',['Ostron'],3,'Rare',1,'Ostron'],
  ['Exodia Might','Zaw',['Ostron'],3,'Rare',1,'Ostron'],
  ['Exodia Triumph','Zaw',['Ostron'],3,'Uncommon',1,'Ostron'],
  ['Exodia Valor','Zaw',['Ostron'],3,'Uncommon',1,'Ostron'],
  ['Exodia Contagion','Zaw',['Plague Star'],3,'Legendary',1,'Plague Star'],
  ['Exodia Epidemic','Zaw',['Plague Star'],3,'Legendary',1,'Plague Star'],
  ['Pax Bolt','Kitgun',['Solaris United'],3,'Rare',1,'Solaris'],
  ['Pax Charge','Kitgun',['Solaris United'],3,'Rare',1,'Solaris'],
  ['Pax Seeker','Kitgun',['Solaris United'],3,'Rare',1,'Solaris'],
  ['Pax Soar','Kitgun',['Solaris United'],3,'Rare',1,'Solaris'],
  ['Arcane Consequence','Warframe',['Teralyst','Orphix'],5,'Common',1,'Eidolon'],
  ['Arcane Deflection','Warframe',['Teralyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Healing','Warframe',['Teralyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Ice','Warframe',['Teralyst','Orphix'],5,'Common',1,'Eidolon'],
  ['Arcane Momentum','Warframe',['Teralyst','Orphix'],5,'Common',1,'Eidolon'],
  ['Arcane Nullifier','Warframe',['Teralyst','Orphix'],5,'Common',1,'Eidolon'],
  ['Arcane Resistance','Warframe',['Teralyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Tempo','Warframe',['Teralyst','Orphix'],5,'Common',1,'Eidolon'],
  ['Arcane Victory','Warframe',['Teralyst','Orphix'],5,'Uncommon',1,'Eidolon'],
  ['Arcane Warmth','Warframe',['Teralyst','Orphix'],5,'Common',1,'Eidolon'],
  ['Arcane Circumvent','Warframe',['The Descendia'],5,'Rare',1,'The Descendia'],
  ['Arcane Concentration','Warframe',['The Descendia'],5,'Rare',1,'The Descendia'],
  ['Arcane Expertise','Warframe',['The Descendia'],5,'Rare',1,'The Descendia'],
  ['Arcane Persistence','Warframe',['The Descendia'],5,'Rare',1,'The Descendia'],
  ['Melee Careen','Melee',['The Descendia'],5,'Rare',1,'The Descendia'],
  ['Primary Bulwark','Primary',['The Descendia'],5,'Rare',1,'The Descendia'],
  ['Primary Debilitate','Primary',['The Descendia'],5,'Rare',1,'The Descendia'],
  ['Primary Overcharge','Primary',['The Descendia'],5,'Rare',1,'The Descendia'],
  ['Secondary Irradiate','Secondary',['The Descendia'],5,'Rare',1,'The Descendia'],
  ['Zid-An Asheir','Tektolyst Artifacts',['The Perita Rebellion'],5,'Rare',1,'The Perita Rebellion'],
  ['Zid-An Haras','Tektolyst Artifacts',['The Perita Rebellion'],5,'Rare',1,'The Perita Rebellion'],
  ['Zid-An Osbok','Tektolyst Artifacts',['The Perita Rebellion'],5,'Rare',1,'The Perita Rebellion'],
  ['Zid-An Sek-Eel','Tektolyst Artifacts',['The Perita Rebellion'],5,'Rare',1,'The Perita Rebellion'],
  ['Zid-An Uskos','Tektolyst Artifacts',['The Perita Rebellion'],5,'Rare',1,'The Perita Rebellion'],
  ['Magus Cadence','Operator',['The Quills'],5,'Uncommon',1,'Ostron'],
  ['Magus Cloud','Operator',['The Quills'],5,'Uncommon',1,'Ostron'],
  ['Magus Elevate','Operator',['The Quills'],5,'Rare',1,'Ostron'],
  ['Magus Husk','Operator',['The Quills'],5,'Common',1,'Ostron'],
  ['Magus Nourish','Operator',['The Quills'],5,'Rare',1,'Ostron'],
  ['Magus Replenish','Operator',['The Quills'],5,'Uncommon',1,'Ostron'],
  ['Magus Vigor','Operator',['The Quills'],5,'Common',1,'Ostron'],
  ['Virtuos Fury','Amp',['The Quills'],3,'Uncommon',1,'Ostron'],
  ['Virtuos Ghost','Amp',['The Quills'],3,'Rare',1,'Ostron'],
  ['Virtuos Null','Amp',['The Quills'],3,'Common',1,'Ostron'],
  ['Virtuos Shadow','Amp',['The Quills'],3,'Rare',1,'Ostron'],
  ['Virtuos Strike','Amp',['The Quills'],3,'Uncommon',1,'Ostron'],
  ['Virtuos Tempo','Amp',['The Quills'],3,'Common',1,'Ostron'],
  ['Cascadia Accuracy','Secondary',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Cascadia Empowered','Secondary',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Cascadia Flare','Secondary',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Cascadia Overcharge','Secondary',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Emergence Dissipate','Operator',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Emergence Renewed','Operator',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Emergence Savior','Operator',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Eternal Eradicate','Amp',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Eternal Logistics','Amp',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Eternal Onslaught','Amp',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Fractalized Reset','Primary',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Molt Augmented','Warframe',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Molt Efficiency','Warframe',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Molt Reconstruct','Warframe',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Molt Vigor','Warframe',['The Zariman'],5,'Rare',1,'Holdfasts'],
  ['Magus Accelerant','Operator',['Vox Solaris'],5,'Common',1,'Solaris'],
  ['Magus Anomaly','Operator',['Vox Solaris'],5,'Common',1,'Solaris'],
  ['Magus Destruct','Operator',['Vox Solaris'],5,'Rare',1,'Solaris'],
  ['Magus Drive','Operator',['Vox Solaris'],5,'Common',1,'Solaris'],
  ['Magus Firewall','Operator',['Vox Solaris'],5,'Common',1,'Solaris'],
  ['Magus Glitch','Operator',['Vox Solaris'],5,'Uncommon',1,'Solaris'],
  ['Magus Lockdown','Operator',['Vox Solaris'],5,'Rare',1,'Solaris'],
  ['Magus Melt','Operator',['Vox Solaris'],5,'Rare',1,'Solaris'],
  ['Magus Overload','Operator',['Vox Solaris'],5,'Common',1,'Solaris'],
  ['Magus Repair','Operator',['Vox Solaris'],5,'Uncommon',1,'Solaris'],
  ['Magus Revert','Operator',['Vox Solaris'],5,'Rare',1,'Solaris'],
  ['Virtuos Forge','Amp',['Vox Solaris'],3,'Uncommon',1,'Solaris'],
  ['Virtuos Spike','Amp',['Vox Solaris'],3,'Common',1,'Solaris'],
  ['Virtuos Surge','Amp',['Vox Solaris'],3,'Common',1,'Solaris'],
  ['Virtuos Trojan','Amp',['Vox Solaris'],3,'Uncommon',1,'Solaris'],
];

// Arcane descriptions — used as tooltips on arcane cards
const ARCANE_DESC = {
  'Primary Deadhead':'On Headshot Kill: +120% Damage for 24s. Stacks up to 3x. +30% to Headshot Multiplier -50% Weapon Recoil',
  'Primary Dexterity':'On Melee Kill: +60% Damage for 20s. Stacks up to 6x. +7.5s Combo Duration',
  'Primary Merciless':'On Kill: +30% Damage for 4s. Stacks up to 12x. +30% Reload Speed',
  'Secondary Deadhead':'On Precision Headshot Kill: +120% Damage for 24s. Stacks up to 3x. +30% to Headshot Multiplier -50% Weapon Recoil',
  'Secondary Dexterity':'On Melee Kill: +60% Damage for 20s. Stacks up to 6x. +7.5s Combo Duration',
  'Secondary Merciless':'On Kill: +30% Damage for 4s. Stacks up to 12x. +30% Reload Speed',
  'Arcane Blade Charger':'On Primary Weapon Kill: 30% chance for +300% Melee Damage for 12s',
  'Arcane Bodyguard':'On 6 Melee Kills within 30s: Heal Companion for 900',
  'Arcane Pistoleer':'On Pistol Headshot Kill: 60% chance for +102% Ammo Efficiency for 12s',
  'Arcane Primary Charger':'On Melee Kill: 30% chance for +300% Primary Weapon Damage for 12s',
  'Arcane Tanker':'On Archgun Equipped: +1200 Armor for 60s',
  'Arcane Battery':'Gain 0.30 maximum Energy per Armor point up to 1000 Energy.',
  'Arcane Ice Storm':'On Enemy Frozen: Gain +2% Ability Strength and +2% Ability Duration for 15s. Stacks up to 20x.',
  'Melee Afflictions':'Enemies affected by Status Effects gain 6 additional stacks when they\'re knocked down or flung by melee attacks.',
  'Secondary Fortifier':'Gain 1 Overguard for every 100 Damage dealt to an enemy\'s Overguard. Deals x8 Extra Damage to Overguard.',
  'Secondary Surge':'On Ability Cast: Next shot gains a Damage Multiplier for every 200 current Energy up to x8.',
  'Melee Animosity':'On Melee Hit: Gain 42% Critical Chance on your next Heavy Attack up to 420%',
  'Melee Crescendo':'On Finisher Kill: Gain 6 Initial Combo for the rest of your mission',
  'Melee Duplicate':'On Base Critical Hits: 100% chance for your attack to strike a second time',
  'Melee Exposure':'On Ability Cast: Gain 60% Corrosive Damage on Melee strikes for 25s. Stacks up to 240%.',
  'Melee Fortification':'On Melee Kill: +210 Armor for 10s',
  'Melee Influence':'On Melee Electricity Status: 20% chance for elemental Melee Status Effects to apply to enemies within 20m for 18s. Cannot refresh while active.',
  'Melee Retaliation':'Gain 30% Melee Damage for every 200 current Shields up to 420%. Bonus halved for Overshields.',
  'Melee Vortex':'Kill an enemy affected by Magnetic Status for a 45% chance to pull in enemies within 18m radius',
  'Arcane Blessing':'On Health Pickup: +24 Max Health. Stacks up to 50x.',
  'Arcane Rise':'On Reload: 60% chance for +150% Damage to Primary Weapons for 24s',
  'Conjunction Voltage':'On Electricity Status Effect: +1.5% Reload Speed and +3% Multishot for 12s. Stacks up to 40x.',
  'Primary Frostbite':'On Cold Status Effect: +3% Critical Damage and +2.25% Multishot for 12s. Stacks up to 40x.',
  'Akimbo Slip Shot':'While sliding or aim gliding: Gain 65% ammo efficiency with Dual Pistols.',
  'Arcane Intention':'Gain +250 Max Health per active channeled ability.',
  'Arcane Power Ramp':'On Ability Cast: Next Ability cast gains +9% Ability Strength stacking up to 4x. Resets when the same ability is recast consecutively.',
  'Arcane Reaper':'On Melee Kill: +24 Health Regen/s and +660 Armor for 10s.',
  'Longbow Sharpshot':'On Headshot: Gain +300% damage on your next shot.',
  'Magus Aggress':'On Warframe Melee Transference: Heavy Blades deal +300% Critical Damage for 4 consecutive attacks. Cooldown 20s.',
  'Primary Blight':'On Toxin Status Effect: +3.6% Critical Damage and +1.8% Multishot for 12s. Stacks up to 40x.',
  'Primary Exhilarate':'On Weapon Impact Status Effect: +1.2 Energy Regen/s for 10s. Stacks up to 3x.',
  'Primary Obstruct':'On Weapon Magnetic Status Effect: Enemy weapons jam within 15m of target. Cooldown 10s.',
  'Secondary Outburst':'On swapping to Secondary Weapon consume all Combo Multipliers to increase Secondary Weapon Critical Chance and Critical Damage by 20% per Combo consumed for 30s.',
  'Secondary Shiver':'Enemies take +45% damage per Cold Status',
  'Shotgun Vendetta':'On shotgun kill within 5m of target: +180% Multishot and +75% Reload Speed for 15s.',
  'Arcane Acceleration':'On Critical Hit: 30% chance for +90% Fire Rate to Primary Weapons (Excludes Shotguns) for 9s',
  'Arcane Aegis':'On Shield Damaged: 3% chance for +30% Shield Recharge for 12s',
  'Arcane Agility':'On Damaged: 60% chance for +60% Parkour Velocity for 18s',
  'Arcane Awakening':'On Reload: 60% chance for +150% Damage to Pistols for 24s',
  'Arcane Eruption':'On Energy Pickup: 100% chance to Knockdown nearby enemies',
  'Arcane Guardian':'On Damaged: 15% chance for +900 Armor for 20s',
  'Arcane Phantasm':'On Block: 45% chance for +60% Speed for 18s',
  'Arcane Precision':'On Headshot: +300% Damage for 18s on Secondary Weapon',
  'Arcane Pulse':'On Health Pickup: 60% chance to restore 500 Health to allies within 25m 15s cooldown',
  'Arcane Strike':'On Hit: 15% chance for +60% Attack Speed to Melee Weapons for 18s',
  'Arcane Ultimatum':'On Finisher Kill: +1200 Armor for 45s',
  'Arcane Bellicose':'Gain 6% Ability Strength for every 250 Max Health up to 72%.',
  'Arcane Camisado':'Attacks from summoned minions increase Ability Strength by 6% up to 60% on the next Ability Cast. Summons gain 20% Movement Speed.',
  'Arcane Crepuscular':'While invisible gain +30% Ability Strength and +3x Final Critical Damage.',
  'Arcane Escapist':'On Mercy Kill: Gain a stack of Escapist up to 9x. On taking fatal damage consume 3 stacks to avoid death and become invulnerable for 12s.',
  'Arcane Hot Shot':'Gain 6% weapon Critical Chance for 10s when using abilities to inflict Heat Status effect on enemies. Maximum 50x stacks.',
  'Arcane Impetus':'Unique Status Effects from Abilities grant +6% Ability Strength and +3% Ability Efficiency for 20s.',
  'Arcane Truculence':'When gaining 3000 or more Overguard threshold release a 30m Radial Attack that applies max Viral Status stacks.',
  'Arcane Universal Fallout':'Each Radiation Status Effect inflicted on enemies by Abilities gives a 6% chance to drop a Universal Orb on enemy death.',
  'Melee Doughty':'Gain 1.0x Critical Damage for every 10% Puncture Status chance on your Melee Weapon.',
  'Primary Crux':'On Weak Point Hit: Gain +30% Status Chance and +6% Ammo Efficiency for 10s. Stacks up to 10x.',
  'Secondary Enervate':'On Hit: Increase Critical Chance by 10%. Resets after 6 Big Critical Hit.',
  'Arcane Arachne':'On Wall Latch: +150% Damage to Primary and Secondary weapons for 30s',
  'Arcane Avenger':'On Damaged: 21% chance for +45% Critical Chance for 12s',
  'Arcane Barrier':'On Shield Damaged: 6% chance to instantly restore all Shields 6s cooldown',
  'Arcane Energize':'On Energy Pickup: 60% chance to replenish 150 Energy to self and allies within 15m 15s cooldown',
  'Arcane Fury':'On Critical Hit: 60% chance for +180% Melee Damage to Melee Weapons for 18s',
  'Arcane Grace':'On Health Damaged: 9% chance for +6% Health Regeneration/s for 9s',
  'Arcane Rage':'On Headshot: 15% chance for +180% Damage to Primary Weapons for 24s',
  'Arcane Trickery':'On Finisher Kill: 15% chance to become invisible for 30s',
  'Arcane Velocity':'On Critical Hit: 90% chance for +120% Fire Rate to Pistols for 9s',
  'Residual Boils':'On Kitgun Kill: 20% chance to spawn volatile hives for 12s that explode when enemies approach for 80 Heat Damage in 10m. Standing in the area applies Heat Damage type to Theorem Arcanes.',
  'Residual Malodor':'On Kitgun Kill: 20% chance to create a frigid mist for 12s dealing 40 Cold Damage/s. Standing in the area applies Cold Damage to Theorem Arcanes.',
  'Residual Shock':'On Kitgun Kill: 20% chance to spawn an electrified spike for 12s dealing 200 Electricity Damage to enemies within 10m. Standing in the area applies Electricity Damage to Theorem Arcanes.',
  'Residual Viremia':'On Kitgun Kill: 20% chance to create pool of toxic blood for 12s dealing 40 Toxin Damage/s. Standing in the area applies the Toxin Damage to Theorem Arcanes.',
  'Theorem Contagion':'Standing in a zone created by a Residual Arcane creates a globe that orbits the player every 2s. The globes will strike the nearest enemy within 15m dealing 150 damage increasing their vulnerability to the globe\'s damage type by 200% for 6s. Globes will persist for 30s upon leaving the zone.',
  'Theorem Demulcent':'Standing in a zone created by a Residual Arcane increases weapon damage by 12%/s stacking up to 15x. Effect persists for 20s upon leaving the zone.',
  'Theorem Infection':'Standing in a zone created by a Residual Arcane increases damage of companions and summoned allies within 90m by 24%/s stacking up to 15x. Effect persists for 20s upon leaving the zone.',
  'Arcane Double Back':'Gain +25% damage resistance for 4s per Dodge Double Jump and Bullet Jump. Stacks up to 3x.',
  'Arcane Steadfast':'On Ability Cast: 20% chance that the next three Abilities will not cost Energy.',
  'Primary Plated Round':'On Reload: Deal increased damage per round loaded based on max magazine size. Lasts for 10s.',
  'Secondary Encumber':'On Status Effect: +24% chance to trigger a second random Status Effect.',
  'Secondary Kinship':'While Buffing Ally Warframes: +20% Critical Chance per buff',
  'Exodia Brave':'On Heavy Attack Kill: +5 Energy Rate for 4s. Stacks up to 3x.',
  'Exodia Force':'On Status Effect: 50% chance to deal 200% Weapon Damage to enemies within 6m.',
  'Exodia Hunt':'On Ground Slam: 50% chance to pull enemies within 12m into melee range.',
  'Exodia Might':'On Finisher Kill: 50% chance for +30% Life Steal for 8s',
  'Exodia Triumph':'+50% Additional Combo Count Chance',
  'Exodia Valor':'+200% Additional Combo Count Chance on Lifted enemies',
  'Exodia Contagion':'After a Bullet Jump or Double Jump: Melee while Aim Gliding launches a projectile that explodes on impact',
  'Exodia Epidemic':'After a Bullet Jump or Double Jump: Slam emits a shockwave forwards that suspends enemies in the air for a short period',
  'Pax Bolt':'On Headshot Kill: +30% Ability Efficiency and +30% Ability Strength on the next Ability used within 4s.',
  'Pax Charge':'Battery Recharge Delay is reduced by +50%',
  'Pax Seeker':'On Headshot Kill: 4 projectiles burst from the target and seek the heads of nearby enemies.',
  'Pax Soar':'+50% Accuracy while Airborne -50% Weapon Recoil while Airborne +5s Aim Glide/Wall Latch Duration',
  'Arcane Consequence':'On Headshot: +60% Parkour Velocity for 18s',
  'Arcane Deflection':'+102% chance to resist a Slash Status effect.',
  'Arcane Healing':'+102% chance to resist a Radiation Status effect.',
  'Arcane Ice':'+102% chance to resist a Heat Status effect.',
  'Arcane Momentum':'On Critical Hit: 60% chance for +150% Reload Speed to Sniper Rifles for 12s',
  'Arcane Nullifier':'+102% chance to resist a Magnetic Status effect.',
  'Arcane Resistance':'+102% chance to resist a Toxin Status effect.',
  'Arcane Tempo':'On Critical Hit: 15% chance for +90% Fire Rate to Shotguns for 12s',
  'Arcane Victory':'On Headshot Kill: 75% chance for +3% Health Regeneration/s for 9s',
  'Arcane Warmth':'+102% chance to resist a Cold Status effect.',
  'Arcane Circumvent':'Roll through enemies to steal 50% of their defenses for yourself. Stolen Armor lasts 15s.',
  'Arcane Concentration':'On Ability Cast: +60% Ability Duration for 3s',
  'Arcane Expertise':'100% of Ability Strength modifiers are also applied to Max Shields.',
  'Arcane Persistence':'Remove all Shields. If Armor is above 700: Cannot be hit for more than 500 Damage/s. Magnetic Status and Ability Nullifying Effects disable this protection.',
  'Melee Careen':'x2.50 Melee Damage against Frozen enemies. On Roll: Freeze enemies in a 5.5m radius with a 2s Cooldown.',
  'Primary Bulwark':'Gain +1% damage for each unit of armor past 1000 up to a max of +500%.',
  'Primary Debilitate':'If an enemy has 10 stacks of a combined Status Effect inflicting the same Status Effect again has a 100% chance to inflict one of the base Status Effects it is composed of.',
  'Primary Overcharge':'While at or above 90% Energy: Gain 35% of Max Energy as Multishot capped at 350%.',
  'Secondary Irradiate':'On hitting enemies afflicted by 10 stacks of Radiation: Deal 180% of the hit damage to enemies within 7m.',
  'Zid-An Asheir':'6% Status chance for all Warframe weapons for each enemy hit with Tauron Strike up to 300%. Buff lasts for 30s +18% Tauron Strike Initial Charge.',
  'Zid-An Haras':'48% Warframe Ammo Efficiency for 30s after executing Tauron Strike +18% Amp Ammo Efficiency',
  'Zid-An Osbok':'Void Sling strips 30% of enemy Overguard. When Overguard is stripped: +3.0x Amp Critical Damage for 15s.',
  'Zid-An Sek-Eel':'Gain invisiblity for 30s after activating Tauron Strike +9% Tauron Strike Charge Rate',
  'Zid-An Uskos':'On Operator and Tauron Strike Kill: 2.4% Heat Damage for Secondary Weapon for duration of mission max 250%',
  'Magus Cadence':'On Void Sling: +90% Sprint Speed for 12s',
  'Magus Cloud':'On Void Mode: +300% Void Sling Radius for 6s',
  'Magus Elevate':'On Transference In: 95% chance to restore 300 Health to Warframe',
  'Magus Husk':'On Transference Out: +300 Armor',
  'Magus Nourish':'While An Operator: Restores 35 Health/s to Warframe.',
  'Magus Replenish':'On Void Sling: Heal 30% Health',
  'Magus Vigor':'On Transference Out: +600 Health',
  'Virtuos Fury':'On Status Effect: 20% chance for +30% Damage for 4s',
  'Virtuos Ghost':'On Headshot: 40% chance for +60% Status Chance for 12s',
  'Virtuos Null':'On Kill: +20% Amp Energy Regeneration for 4s',
  'Virtuos Shadow':'On Headshot: 40% chance for +60% Critical Chance for 12s',
  'Virtuos Strike':'On Critical Hit: 20% chance for +80% Critical Damage for 4s',
  'Virtuos Tempo':'On Kill: 60% chance for +60% Fire Rate for 8s',
  'Cascadia Accuracy':'On Roll: +300% Critical Chance on Weakpoint Hits for 4s',
  'Cascadia Empowered':'On Status Effect: Deals +750 Damage matching the Damage Type of the Status Effect',
  'Cascadia Flare':'On Heat Status Effect: +12% Damage for 10s. Stacks up to 480%.',
  'Cascadia Overcharge':'While Overshields Active: +300% Critical Chance',
  'Emergence Dissipate':'While in Void Sling: Press <PRE_ATTACK> to dissipate the endpoint in a 10m radius. Enemies hit create a short lived Void Mote that replenishes 10 Energy on pick up.',
  'Emergence Renewed':'On Energy Depleted: Increase Energy Regeneration by 300% over 5s. Cooldown: 30s',
  'Emergence Savior':'On Lethal Damage: Become invulnerable for 5s and recover 60% Health. Cooldown: 90s',
  'Eternal Eradicate':'On Operator Ability: +60% Damage to Amps for 8s',
  'Eternal Logistics':'On Void Sling: +72% Amp Ammo Efficiency for 8s',
  'Eternal Onslaught':'On Energy Depleted: 180% Critical Chance for 8s',
  'Fractalized Reset':'On Ability Cast: +240% Reload Speed for 5s',
  'Molt Augmented':'On Kill: +0.24% Ability Strength. Stacks up to 250x.',
  'Molt Efficiency':'While Shields are Active: Gain 6% Ability Duration per second up to a maximum of 36%',
  'Molt Reconstruct':'Heal yourself and allies within Affinity Range 6 Health for each Energy point spent on the initial casting cost of abilities.',
  'Molt Vigor':'On Operator Ability: 45% Ability Strength on next Warframe Ability Cast',
  'Magus Accelerant':'On Void Sling: Reduce Enemy Resistance to Heat Damage by 65%.',
  'Magus Anomaly':'On Transference In: Enemies within 30m are pulled towards Warframe.',
  'Magus Destruct':'On Void Sling: Reduce Enemy Resistance to Puncture Damage by 65%.',
  'Magus Drive':'On Transference In: Increase K-Drive Speed by 150% for 30s.',
  'Magus Firewall':'On Void Mode: Generate Void Particles every 1s up to 6 particles each granting 12.5% Damage Reduction for 60s. Taking damage consumes a particle.',
  'Magus Glitch':'On Transference Static: 102% chance to negate Transference Static.',
  'Magus Lockdown':'On Void Sling: Drop a mine that tethers up to 10 enemies in 15m for 4s.',
  'Magus Melt':'On Void Sling: Increase Heat Damage in Operator Mode by 30% for 15s stacking up to 7x.',
  'Magus Overload':'On Void Sling: Stun robotic enemies for 3s which then discharge Electricity Damage dealing 80% of their Max Health to anyone within 25m.',
  'Magus Repair':'On Void Mode: Heal Warframes within 30m by 25% Health/s.',
  'Magus Revert':'On Void Sling: Use again within 3s to return the Operator to their original position at no energy cost. Restores 60 Health. 3s cooldown.',
  'Virtuos Forge':'On Hit: Converts 98% Void Damage to Heat Damage.',
  'Virtuos Spike':'On Hit: Converts 98% Void Damage to Puncture Damage.',
  'Virtuos Surge':'On Hit: Converts 98% Void Damage to Electricity Damage.',
  'Virtuos Trojan':'On Hit: Converts 98% Void Damage to Viral Damage.',
};

